TestProfile:
	g++ -O2 -o TestProfile -I ../../include TestProfile.cpp ../impl/DefaultProfileReader.cpp ../impl/DefaultProfileWriter.cpp ../raii/CharBuffer.cpp ../raii/FilePtr.cpp ../core/VProfileReader.cpp ../core/VProfileWriter.cpp ../data/data.cpp
TestLayouter:
	g++ -O2 -o TestLayouter -I ../../include TestLayouter.cpp ../impl/ScaledLayouter.cpp ../util/Bitmap.cpp ../data/data.cpp  ../core/Vlayouter.cpp
TestImage:
	g++ -O2 -o TestImage -I ../../include TestImage.cpp ../impl/Image.cpp ../impl/ImageReader.cpp ../impl/ImageWriter.cpp ../core/VImage.cpp ../core/VImageReader.cpp ../core/VImageWriter.cpp ../data/data.cpp
TestBitmap:
	g++ -O2 -o TestBitmap -I ../../include TestBitmap.cpp ../util/Bitmap.cpp